version: '3'

networks:
    sail:
        driver: bridge
        external: true

services:
    node:
        build:
            context: .
        env_file:
            - .env
        command: bash -c "npm install && npm run dev"
        volumes:
            - .:/app
        networks:
            - sail
