version: '3'

networks:
    sail:
        driver: bridge
        external: true
    event-processor:
        driver: bridge
        external: false

services:
    node:
        build:
            context: .
        env_file:
            - .env
        command: bash -c "npm install && npm run dev"
        volumes:
            - .:/app
        networks:
            - event-processor
            - sail
        depends_on:
            - redis

    redis:
        image: 'redis'
        hostname: eventredis
        expose:
            - 6379
        volumes:
            - 'event-redis:/data'
        networks:
            - event-processor
            - sail

volumes:
    event-redis:
        driver: local
