version: '3'

networks:
    sail:
        driver: bridge
        external: true

services:
    node:
        build:
            context: .
        environment:
            NODE_ENV: development
        env_file:
            - .env
        ports:
            - "3000:3000"
        command: bash -c "npm install && npm run dev"
        volumes:
            - .:/app
        networks:
            - sail
